### PR TITLE
Sort and filter comment replies the same as root comments

### LINKED ISSUE #1397: Blocked users' comments still visible in the Interstellar app
**Describe the bug**
Blocked users' comments are still visible in the Interstellar app [please see additional context]

**On which Mbin instance did you find the bug?**
kbin.earth

**Which Mbin version was running on the instance?**
1.7.4

**To Reproduce**
1. Block some obnoxious reply guy
2. In Interstellar, navigate to communities where you encountered them in the past
3. Find them in the comment section

I did a side-by-side comparison of the same thread in the web UI and in Interstellar: in the browser blocked users' comments were hidden, in the app they were shown.

**Expected behavior**
I expect blocked users to not be shown at top or comment level, in the web UI or apps.

**Smartphone:**
 - Device: Fairphone 4
 - OS: LineageOS for MicroG 22.1
 - Browser Fennec
 - Browser Version: 134.0.0

**Additional context**
I raised this issue [in the Interstellar repo](https://github.com/jwr1/interstellar/issues/92), and the developer asked me to report it here as well. I hope you guys can hash it out?

### PR DESCRIPTION
**Pull request by BentiGorlich**
- pass the criteria through to match child comments by it
- included criteria:
  - ordering
  - banned hashtag checking
  - preferred languages
  - federation filter (not used with comments, but still included)
  - time filter (also not used for comments atm)
- filter out comments from banned authors

Closes #1397

### CODE REVIEW

File: src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php [hunk 1]
```diff
@@ -152,15 +153,12 @@ public function __invoke(
 
         $comments = $commentsRepository->findByCriteria($criteria);
 
-        $commentsRepository->hydrate(...$comments);
```
[the remark this answers is not in the document]
Comment (BentiGorlich) [reply src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php:155]: I am not 100% sure, but I think it was supposed to fetch everything needed at once instead of fetching the collections one by one... I am not sure if it actually worked in any way shape or form, but that is my guess

[the remark this answers is not in the document]
Comment (melroy89) [reply src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php:155]: I also didn't fully get it, despite the name "hydrate" which is of course a hint. Meaning its pre-loading or preparing something. Just like Angular Hydrate.

In this case it seems that its used in Doctrine to partial load the records in one big good rather than one query at a time, see also: https://github.com/doctrine/orm/issues/8471#issuecomment-2400932188

And also: https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/reference/partial-objects.html

This is normally done to improve the speed & performance, so  Doctrine’s identity map is populated with all needed associations so later access doesn’t trigger additional SQL.

Whether its actually working or not, I do not know, but maybe we should keep it, unless you really know for sure if it has no benefit now.

[the remark this answers is not in the document]
Comment (BentiGorlich) [reply src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php:155]: I can check that when I am at home. With a larger comment tree I should be able to see the queries decrease if it works

[the remark this answers is not in the document]
Comment (BentiGorlich) [reply src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php:155]: I will bring it back. It reduces the DB queries from 278 to 247 on an entry with 40 comments

**Comment by BentiGorlich** [comment]
I have it running on gehirneimer.de

File: src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (melroy89) [reply src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php]: Thank you for your confirmation

File: src/Repository/EntryCommentRepository.php [hunk 2]
```diff
@@ -314,37 +313,4 @@ public function hydrate(EntryComment ...$comments): void
             ->getQuery()
             ->execute();
     }
-
-    public function hydrateParents(EntryComment ...$comments): void
```
Comment (melroy89) [inline src/Repository/EntryCommentRepository.php:318]: Could you also bring back this hydration code?

File: src/Repository/PostCommentRepository.php [hunk 3]
```diff
@@ -221,27 +220,4 @@ public function hydrate(PostComment ...$comment): void
                 ->getResult();
         }
     }
-
-    public function findToDelete(User $user, int $limit): array
```
Comment (melroy89) [inline src/Repository/PostCommentRepository.php:225]: Could you also bring back this hydration code?

Comment (BentiGorlich) [reply src/Repository/PostCommentRepository.php:225]: This is not hydration code

File: src/Repository/EntryCommentRepository.php (hunk 2 above)
Comment (BentiGorlich) [reply src/Repository/EntryCommentRepository.php:318]: This was just not used, so I think it is not necessary...

Comment (melroy89) [reply src/Repository/EntryCommentRepository.php:318]: Ow. Maybe we could now leverage hydration to reduce the db calls. Now you know it actually works?

Could we call this method?

Comment (BentiGorlich) [reply src/Repository/EntryCommentRepository.php:318]: I cannot think of a place where this might be useful... We basically always already have the parent of a comment and we can hydrate that with the method in the EntryRepository

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
I'm getting this weird error with Docker now. When I try to use `./docker/setup.sh dev localhost`

I did change the docker image to the main tag: `ghcr.io/mbinorg/mbin:main` in my compose.yaml.

But when running:

```sh
docker compose up -d
```

I see:

```
In FileLoader.php line 356:
                                                                               
  Expected to find class "App\Utils\ArrayUtils" in file "/app/src/Utils/Array  
  Utils.php" while importing services from resource "../src/", but it was not  
   found! Check the namespace prefix used with the resource.                   
                                                                               


In FileLoader.php line 177:
                                                                               
  Expected to find class "App\Utils\ArrayUtils" in file "/app/src/Utils/Array  
  Utils.php" while importing services from resource "../src/", but it was not  
   found! Check the namespace prefix used with the resource in /app/config/se  
  rvices.yaml (which is being imported from "/app/src/Kernel.php").            
                                                                               

In FileLoader.php line 356:
                                                                               
  Expected to find class "App\Utils\ArrayUtils" in file "/app/src/Utils/Array  
  Utils.php" while importing services from resource "../src/", but it was not  
   found! Check the namespace prefix used with the resource.                   
```

Any clue?

**Comment by BentiGorlich** [comment]
As far as I know it is the autoloader generated by composer that fucked up... So rerun `composer install` and restarting php to clear out opcache should fix it

**Comment by melroy89** [comment]
> As far as I know it is the autoloader generated by composer that fucked up... So rerun `composer install` and restarting php to clear out opcache should fix it

This is what the script should do by default in docker. Right @jwr1? It seems we missed something with the docker setup.

**Comment by BentiGorlich** [comment]
I thought that that fixed it for me locally when I was developing (also with docker)... Not sure how I fixed it if it was not with these commands...
