### PR TITLE
Inline all content previews

### LINKED ISSUE #1493: Link previews fail to render if the thread title is included in the URL
**Describe the bug**
Image
*What I wrote*

Image
*What renders*

Image
*HTML contents*

Image
*It gets federated correctly (screenshot taken from the Lemmy instance of the user I replied to)*

As you can see above, it seems Mbin tries to replace my link with something else but fails and only inserts a div despite removing the actual link, completely swallowing the actual link.

**On which Mbin instance did you find the bug?**
kbin.earth

**Which Mbin version was running on the instance?**
1.8.0

**To Reproduce**
Create a comment containing this link: https://kbin.earth/m/fediversenews@piefed.social/t/976189/PieFed-adds-multi-reddit-multi-community-feature/favourites

**Expected behavior**
Either my link stays intact or gets replaced with the new inline preview feature, either way I expect it to display in some manner.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Browser Version:  132.0.2957.140

**Additional context**
[Link to the comment](https://kbin.earth/m/technology@lemmy.world/t/1006524/-/comment/5401565)
There's no errors in the console.

### PR DESCRIPTION
**Pull request by BentiGorlich**
- make them inline, so when you have `look here (some content link)` it does not get converted to: ``` look here ( some content preview ) ```
- fix links getting completely removed. The cause was the link-matching in the `ApActivityRepository` which sometimes returned an object with `0` as the id which of course does not yield results from the DB. Since that was just not expected we showed an empty div for these links
grafik

Closes #1493

### CODE REVIEW

**Comment by melroy89** [comment]
See it in action as well here: https://kbin.melroy.org/m/testing/t/728880/Test-markdown

It does seem to work now indeed! Thanks. It only doesn't work when the span is too large like a big title or something. Then the span will just be too large and cause the text to wrap anyways (or even the inside text in the span will wrap).

**Review by melroy89 — APPROVED** [review]

File: tests/Unit/Utils/MarkdownTest.php [hunk 1]
```diff
@@ -89,4 +92,49 @@ public function testExternalMentionLink(): void
         // assert that this community does not exist, and we get a search link for it that does not link to the external instance
         self::assertStringContainsString('https://kbin.test2', $markdown);
     }
+
+    public function testExternalMagazineLocalPostLink(): void
```
Comment (melroy89) [inline tests/Unit/Utils/MarkdownTest.php:96]: 👍🏽  for an additional test.

File: src/Repository/ApActivityRepository.php [hunk 2]
```diff
@@ -95,6 +95,10 @@ public function findLocalByApId(string $apId): ?array
                         'type' => Post::class,
                     ];
                 } else {
+                    if (0 === $id) {
```
Comment (melroy89) [inline src/Repository/ApActivityRepository.php:98]: Maybe also explain this code, just for future references so we still understand why this was added.

```suggestion
                    // Ignore processing $id of zero, because ...
                    if (0 === $id) {
```

File: src/Repository/ApActivityRepository.php [hunk 3]
```diff
@@ -108,7 +112,17 @@ public function findLocalByApId(string $apId): ?array
...
                         'type' => Entry::class,
                     ];
+                } elseif (5 === \count($exploded)) {
+                    // entry url with slug (non-ap route)
+                    return [
+                        'id' => \intval($exploded[4]),
+                        'type' => Entry::class,
+                    ];
                 } else {
+                    if (0 === $id) {
```
Comment (melroy89) [inline src/Repository/ApActivityRepository.php:122]: Same here :)

Comment (BentiGorlich) [reply src/Repository/ApActivityRepository.php:124]: done :)

**Review by melroy89 — APPROVED** [review]
