### PR TITLE
DeleteUserHandler: roll back nested transaction if any exception occurs.

### LINKED ISSUE #1846: HandleMessageMiddleware might try to create a transaction within a transation
Handling of an ActivityPub message can fail with `There is already an active transaction`

Loglines:
```json
{
  "message": "Error thrown while handling message App\\Message\\Notification\\FavouriteNotificationMessage. Sending for retry #1 using 300000 ms delay. Error: \"Handling \"App\\Message\\Notification\\FavouriteNotificationMessage\" failed: There is already an active transaction\"",
  "context": {
    "class": "App\\Message\\Notification\\FavouriteNotificationMessage",
    "message_id": null,
    "retryCount": 1,
    "delay": 300000,
    "error": "Handling \"App\\Message\\Notification\\FavouriteNotificationMessage\" failed: There is already an active transaction",
    "exception": {
      "class": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
      "message": "Handling \"App\\Message\\Notification\\FavouriteNotificationMessage\" failed: There is already an active transaction",
      "code": 0,
      "file": "/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124",
      "previous": {
        "class": "Doctrine\\DBAL\\Driver\\PDO\\PDOException",
        "message": "There is already an active transaction",
        "code": 0,
        "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/PDOException.php:16",
        "previous": {
          "class": "PDOException",
          "message": "There is already an active transaction",
          "code": 0,
          "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:117"
        }
      }
    }
  },
  "level": 300,
  "level_name": "WARNING",
  "channel": "messenger",
  "datetime": "2025-11-05T00:25:48.229626+00:00",
  "extra": {}
}
```

```json
{
  "message": "Error thrown while handling message App\\Message\\ActivityPub\\Inbox\\ActivityMessage. Sending for retry #1 using 300000 ms delay. Error: \"Handling \"App\\Message\\ActivityPub\\Inbox\\ActivityMessage\" failed: There is already an active transaction\"",
  "context": {
    "class": "App\\Message\\ActivityPub\\Inbox\\ActivityMessage",
    "message_id": null,
    "retryCount": 1,
    "delay": 300000,
    "error": "Handling \"App\\Message\\ActivityPub\\Inbox\\ActivityMessage\" failed: There is already an active transaction",
    "exception": {
      "class": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
      "message": "Handling \"App\\Message\\ActivityPub\\Inbox\\ActivityMessage\" failed: There is already an active transaction",
      "code": 0,
      "file": "/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124",
      "previous": {
        "class": "Doctrine\\DBAL\\Driver\\PDO\\PDOException",
        "message": "There is already an active transaction",
        "code": 0,
        "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/PDOException.php:16",
        "previous": {
          "class": "PDOException",
          "message": "There is already an active transaction",
          "code": 0,
          "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:117"
        }
      }
    }
  },
  "level": 300,
  "level_name": "WARNING",
  "channel": "messenger",
  "datetime": "2025-11-05T00:25:48.283909+00:00",
  "extra": {}
}
```
```json
{
  "message": "Error thrown while handling message App\\Message\\ActivityPub\\Inbox\\DislikeMessage. Sending for retry #1 using 300000 ms delay. Error: \"Handling \"App\\Message\\ActivityPub\\Inbox\\DislikeMessage\" failed: There is already an active transaction\"",
  "context": {
    "class": "App\\Message\\ActivityPub\\Inbox\\DislikeMessage",
    "message_id": null,
    "retryCount": 1,
    "delay": 300000,
    "error": "Handling \"App\\Message\\ActivityPub\\Inbox\\DislikeMessage\" failed: There is already an active transaction",
    "exception": {
      "class": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
      "message": "Handling \"App\\Message\\ActivityPub\\Inbox\\DislikeMessage\" failed: There is already an active transaction",
      "code": 0,
      "file": "/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124",
      "previous": {
        "class": "Doctrine\\DBAL\\Driver\\PDO\\PDOException",
        "message": "There is already an active transaction",
        "code": 0,
        "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/PDOException.php:16",
        "previous": {
          "class": "PDOException",
          "message": "There is already an active transaction",
          "code": 0,
          "file": "/app/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:117"
        }
      }
    }
  },
  "level": 300,
  "level_name": "WARNING",
  "channel": "messenger",
  "datetime": "2025-11-05T00:25:48.284113+00:00",
  "extra": {}
}
```

### PR DESCRIPTION
**Pull request by blued-gear**
This is the only place in the codebase where I found an opened transaction without an accompanying rollback.

Might fix #1846

### CODE REVIEW

File: src/MessageHandler/DeleteUserHandler.php [hunk 1]
```diff
@@ -93,30 +93,36 @@ public function doWork(MessageInterface $message): void
...
-        if ($isLocal) {
-            $this->sendDeleteMessages($inboxes, $user);
-        }
+            if ($isLocal) {
+                $this->sendDeleteMessages($inboxes, $user);
+            }
+
+            $this->entityManager->commit();
+        } catch (\Exception $e) {
+            $this->entityManager->rollback();
```
Comment (blued-gear) [inline src/MessageHandler/DeleteUserHandler.php:121]: does this also need a `$this->managerRegistry->resetManager();`? As this is a savepoint (nested transaction), I'm not sure.

Comment (BentiGorlich) [reply src/MessageHandler/DeleteUserHandler.php:121]: I think it is not strictly necessary, as this is the end of the method and the entitymanager will be disposed afterwards anyways...

Comment (melroy89) [reply src/MessageHandler/DeleteUserHandler.php:121]: also if you catched the error?

Comment (blued-gear) [reply src/MessageHandler/DeleteUserHandler.php:121]: it is thrown right after this, so it should not make a difference
