### PR TITLE
improve logs and fix some warnings

### LINKED ISSUE #1858: Undefined variable `$response` in ApHttpClient
Logline:
```json
{
  "message": "Warning: Undefined variable $response",
  "context": {
    "exception": {
      "class": "ErrorException",
      "message": "Warning: Undefined variable $response",
      "code": 0,
      "file": "/app/src/Service/ActivityPub/ApHttpClient.php:449"
    }
  },
  "level": 400,
  "level_name": "ERROR",
  "channel": "php",
  "datetime": "2025-11-05T00:03:11.266288+00:00",
  "extra": {}
}
```

### LINKED ISSUE #1859: Undefined array key 0 in MentionManager
Logline:
```json
{
  "message": "Warning: Undefined array key 0",
  "context": {
    "exception": {
      "class": "ErrorException",
      "message": "Warning: Undefined array key 0",
      "code": 0,
      "file": "/app/src/Service/MentionManager.php:65"
    }
  },
  "level": 400,
  "level_name": "ERROR",
  "channel": "php",
  "datetime": "2025-11-05T00:10:20.207068+00:00",
  "extra": {}
}
```

### PR DESCRIPTION
**Pull request by blued-gear**
- addresses some points of #1175
- fixes #1858
- fixes #1859

### CODE REVIEW

**Review by melroy89 — APPROVED** [review]
Thank you for this one!

File: src/MessageHandler/DeleteUserHandler.php [hunk 1]
```diff
@@ -54,7 +54,8 @@ public function doWork(MessageInterface $message): void
         if (!$user) {
             throw new UnrecoverableMessageHandlingException('User not found');
         } elseif ($user->isDeleted && null === $user->markedForDeletionAt) {
-            throw new UnrecoverableMessageHandlingException('User already deleted');
+            // user already deleted
```
Comment (melroy89) [inline src/MessageHandler/DeleteUserHandler.php:57]: UnrecoverableMessageHandlingException is for a reason I think.. so it doesn't do a retry..

Comment (BentiGorlich) [reply src/MessageHandler/DeleteUserHandler.php:57]: We could actually decide to not throw the error and just return instead. That would remove the error from the log and the same result would ne achieved (no retries). One could argue that this result logically counts as a success anyways...

Comment (blued-gear) [reply src/MessageHandler/DeleteUserHandler.php:57]: So just to make sure before I merge this: I can let the replacement of the exception with the return as it is?

Comment (melroy89) [reply src/MessageHandler/DeleteUserHandler.php:57]: Ah OK got it.

Yeah. You should be able to keep it like it's now. We just don't get a warning/error about it.

**Review by melroy89 — APPROVED** [review]
