### PR TITLE
Fix magazine log api subject

### LINKED ISSUE #1923: Incorrect moderator listed in modlog API
**Describe the bug**
For `log_moderator_add` and `log_moderator_remove` types the moderator added/removed is listed in the API output rather than the moderator performing the action.

Here is a sample from https://kbin.earth/api/magazine/46/log which shows a `log_moderator_add` log type with myself listed as moderator when, as can be seen here https://kbin.earth/m/testing/modlog, jwr1 is the one adding me as a moderator.
```
{
  "type":"log_moderator_add",
  "createdAt":"2025-06-11T18:01:40+00:00",
  "magazine":{
    "magazineId":46,
    "name":"testing",
    "icon":{
      "filePath":"0c\/b7\/0cb7d72d53122b283c61cb095a62ab28076d5d9171180c6a84ea7828dee7799b.png",
      "sourceUrl":null,
      "storageUrl":"https:\/\/media.kbin.earth\/0c\/b7\/0cb7d72d53122b283c61cb095a62ab28076d5d9171180c6a84ea7828dee7799b.png",
      "altText":null,
      "width":512,
      "height":512,
      "blurHash":"L9A*.z,s1dFx1}J-$4,D1fa|}DWq"
    },
    "banner":null,
    "isUserSubscribed":null,
    "isBlockedByUser":null,
    "apId":null,
    "apProfileId":"https:\/\/kbin.earth\/m\/testing"
  },
  "moderator":{
    "userId":21760,
    "username":"olorin99",
    "isBot":false,
    "isFollowedByUser":null,
    "isFollowerOfUser":null,
    "isBlockedByUser":null,
    "isAdmin":false,
    "isGlobalModerator":false,
    "avatar":{
      "filePath":"b5\/a9\/b5a991d2125f27f86e620b895999d9e53816a63a8ea0a409c4722ffba7fd2fcc.gif",
      "sourceUrl":"https:\/\/media.kbin.social\/media\/b5\/a9\/b5a991d2125f27f86e620b895999d9e53816a63a8ea0a409c4722ffba7fd2fcc.gif",
      "storageUrl":"https:\/\/media.kbin.earth\/b5\/a9\/b5a991d2125f27f86e620b895999d9e53816a63a8ea0a409c4722ffba7fd2fcc.gif",
      "altText":null,
      "width":260,
      "height":215,
      "blurHash":"L14.MGIW00r;%$-p4T9Z~qs:8_IU"
    },
    "apId":null,
    "apProfileId":null,
    "createdAt":"2023-12-28T05:55:45+00:00"
  },
  "subject":null
}
```

**On which Mbin instance did you find the bug?**
kbin.earth

**Which Mbin version was running on the instance?**
1.9.0-rc3

**Expected behavior**
I would expect the moderator performing the action to be listed as moderator and the moderator being added/removed to be listed under subject.

### PR DESCRIPTION
**Pull request by BentiGorlich**
- the subject was not properly set for some types
  - `log_entry_pinned` and `log_entry_unpinned` just didn't have a proper one, they now have an `EntryResponseDto`
  - `log_ban` and `log_unban` also didn't have one, they now have a `MagazineBanResponseDto`
  - `log_moderator_add` and `log_moderator_remove` also didn't have one, they now have an `UserSmallResponseDto`
- fix wrong `moderator` property when type is `log_moderator_add` or `log_moderator_remove`
- fix documentation for the `subject` property not being generated.
- add tests for some of the faulty types

Fixes #1923 and #1931

### CODE REVIEW

File: src/Entity/MagazineLog.php [hunk 1]
```diff
@@ -64,6 +64,13 @@ abstract class MagazineLog
     public Magazine $magazine;
     #[ManyToOne(targetEntity: User::class)]
     #[JoinColumn(nullable: false, onDelete: 'CASCADE')]
+    /**
+     * Usually the acting moderator. There are 2 exceptions MagazineLogModeratorAdd and MagazineLogModeratorRemove,
```
Comment (blued-gear) [inline src/Entity/MagazineLog.php]: I find this sentence a bit ambiguous. My suggestion:

Usually the acting moderator. There are 2 exceptions MagazineLogModeratorAdd and MagazineLogModeratorRemove; in that case this is the moderator being added or removed (because the acting moderator can be null).

File: src/DTO/MagazineLogResponseDto.php [hunk 2]
```diff
@@ -32,39 +31,46 @@ class MagazineLogResponseDto implements \JsonSerializable
...
+        ?UserSmallResponseDto $moderatorSubject = null,
     ): self {
         $dto = new MagazineLogResponseDto();
         $dto->magazine = $magazine;
         $dto->moderator = $moderator;
         $dto->createdAt = $createdAt;
         $dto->type = $type;
         if ('log_ban' === $type || 'log_unban' === $type) {
-            $dto->subject = $subject;
+            $dto->subject2 = $banSubject;
```
Comment (blued-gear) [inline src/DTO/MagazineLogResponseDto.php]: Could you add some checks here? Like asserting that for bans $banSubject is not null but $moderatorSubject is. Inverse of moderator add.

Or maybe even split the different cases up into multiple create() functions and call the appropriate in the matching if-branch in MagazineFactory::createBanDto(). \
So for example createBanUnban() with banSubject, createModAddRemove() with moderatorSubject and a create function for generic cases. Plus a private function where common code parts are placed.
