### PR TITLE
Fix type error on mention extraction from tags

### LINKED ISSUE #2107: Bug: ActivityPub processing fails with `as:Public` and string `to`/`cc`
**Describe the bug**
Mbin fails to process some ActivityPub objects containing `as:Public` or string `to` / `cc` fields.
This results in inbox processing errors and posts not being imported.

**On which Mbin instance did you find the bug?**
bin.pivox.net

**Which Mbin version was running on the instance?**
1.10.0rc1

**To Reproduce**
1. Follow or fetch a post from Ghost CMS or PeerTube
2. Or receive a boost via Mastodon
3. Try to view or import the post in Mbin
4. See error in logs / inbox processing fails

**Expected behavior**
Posts should be imported correctly.
`to` / `cc` should support both string and array formats, and `as:Public` should not be treated as a resolvable actor.

**Screenshots**
N/A (log-based issue)

**Desktop (please complete the following information):**
 - OS: OS: Ubuntu24.04LTS
 - Browser: Firefox
 - Browser Version: 149

**Additional context**
Errors observed:

```text id="q8k1pd"
WebFinger handle is malformed 'as:Public'
```

```text id="v3kz7a"
Cannot access offset of type string on string
```

### PR DESCRIPTION
**Pull request by BentiGorlich**
- ignore something in the tag array if it is not an array or is missing one of the required fields `type`, `name` or `href`

#2107

### CODE REVIEW

File: src/Service/ActivityPub/MarkdownConverter.php [hunk 1]
```diff
@@ -72,6 +72,9 @@ private function findMentionFromTag(array $match, array $apTags): array
     {
         $res = [];
         foreach ($apTags as $tag) {
+            if (!\is_array($tag) || !isset($tag['type']) || !isset($tag['name']) || !isset($tag['href'])) {
+                continue;
```
Comment (blued-gear) [inline src/Service/ActivityPub/MarkdownConverter.php:80]: Instead of just skipping the item, we should log the content (as a warning) to notice if a new type of tag goes around or so.

Comment (BentiGorlich) [reply src/Service/ActivityPub/MarkdownConverter.php:80]: will do :+1:

File: src/Service/ActivityPub/MarkdownConverter.php [hunk 2]
```diff
@@ -72,6 +74,11 @@ private function findMentionFromTag(array $match, array $apTags): array
     {
         $res = [];
         foreach ($apTags as $tag) {
+            if (!\is_array($tag) || !isset($tag['type']) || !isset($tag['name']) || !isset($tag['href'])) {
+                $this->logger->warning('Ignoring tag (not an array or missing "name", "type" or "href": {t}', ['t' => $tag]);
```
Comment (blued-gear) [inline src/Service/ActivityPub/MarkdownConverter.php]:
```suggestion
                $this->logger->warning('Ignoring tag (not an array or missing "name", "type" or "href"): {t}', ['t' => $tag]);
```

**Review by blued-gear — APPROVED** [review]
