### PR TITLE
Fix infinite scroll on user profile and search pages

### LINKED ISSUE #866: Profile overview infinite scroll not working
**Describe the bug**
When you have infinite scroll enabled and go to a profile that has too many posts for one page the infinite scroll will not work when going to the end of the page

**On which Mbin instance did you find the bug?**
[gehirneimer.de]

**Which Mbin version was running on the instance?**
[1.6.0 ~ f37b5968a3df9ab98e40c02a0b0b8803aaba9ae2]

**To Reproduce**
1. Enable infinite scroll
2. Go to an active profile
3. Scroll down to the end of the page
4. Pagination pops up, but not more results

**Expected behavior**
It should add the next posts down there

### PR DESCRIPTION
**Pull request by BentiGorlich**
Fixes #866

### CODE REVIEW

File: assets/controllers/infinite_scroll_controller.js [hunk 1]
```diff
@@ -58,7 +58,8 @@ export default class extends Controller {
         const elements = div.querySelectorAll('[data-controller="subject-list"] > *');
         for (let i = 0; i < elements.length; i++) {
             const element = elements[i];
-            if (element.id && null === document.getElementById(element.id)) {
+            console.log(element)
+            if ((element.id && null === document.getElementById(element.id)) || element.classList.contains('user-box-inline') || element.classList.contains('magazine')) {
```
Comment (blued-gear) [inline assets/controllers/infinite_scroll_controller.js]: console.log() should not be in prod

**Comment by blued-gear** [comment]
I tried it with fixtures and found two problems:
1. when scrolling down *boosts* of a user, the loading indicator shows up, vanishes, at next scroll shows up and sticks there. console has error `Invalid JSON response` (the controller returns html)
2. when a new page is appended to *Overview*, the panes have a slight inset (see image)
3. infinite scroll seems to not apply to *Replies* and *Comments*

inset

**Comment by blued-gear** [comment]
My commented issues seem to be fixed. Point *2* was a not caused by your PR, I now saw that this is only for posts, as they have a left margin.

Would you add a fix in this PR to set the margin to 0 on *overview* so that they align with threads or should this rather be its own PR?

**Comment by BentiGorlich** [comment]
I did that already :)


Am 1. Februar 2026 20:20:40 MEZ schrieb blued_gear ***@***.***>:

**Comment by blued-gear** [comment]
I run your latest commit (daf01c9f) but still see the issue.

screenshot

**Comment by BentiGorlich** [comment]
Are you sure you've compiled the styles and refreshed with clearing the cache? I did not see any insets locally anymore

**Comment by blued-gear** [comment]
Oh, sorry. I forgot to rebuild the FE stuff. Looks good now.

You get the approval once the tests don't fail anymore ;)

**Comment by BentiGorlich** [comment]
Ok nice 👍

**Comment by blued-gear** [comment]
I missed that this will also remove the parent of replies. What was the reason for this decision, as the context might be important for replies?
