### PR TITLE
Fix support for `image` property on `Page` type, add support for string

### LINKED ISSUE #2107: Bug: ActivityPub processing fails with `as:Public` and string `to`/`cc`
**Describe the bug**
Mbin fails to process some ActivityPub objects containing `as:Public` or string `to` / `cc` fields.
This results in inbox processing errors and posts not being imported.

**On which Mbin instance did you find the bug?**
bin.pivox.net

**Which Mbin version was running on the instance?**
1.10.0rc1

**To Reproduce**
1. Follow or fetch a post from Ghost CMS or PeerTube
2. Or receive a boost via Mastodon
3. Try to view or import the post in Mbin
4. See error in logs / inbox processing fails

**Expected behavior**
Posts should be imported correctly.
`to` / `cc` should support both string and array formats, and `as:Public` should not be treated as a resolvable actor.

**Screenshots**
N/A (log-based issue)

**Desktop (please complete the following information):**
 - OS: OS: Ubuntu24.04LTS
 - Browser: Firefox
 - Browser Version: 149

**Additional context**
Errors observed:

```text id="q8k1pd"
WebFinger handle is malformed 'as:Public'
```

```text id="v3kz7a"
Cannot access offset of type string on string
```

### PR DESCRIPTION
**Pull request by BentiGorlich**
- When a `Page` ActivityPub object contains only an `image` property, but no `attachment` property our code threw an error
- Add support for either `attachment` or `image` property to contain only a string (Ghost does this for example)

With this change an AP-Object like this: https://www.shoptechblog.com/.ghost/activitypub/article/38919605-5b90-4b0b-ad3c-5991a889855c
will properly work and get the image attached

Also connection to #2107

### CODE REVIEW

File: src/Service/ActivityPub/Page.php [hunk 1]
```diff
@@ -91,7 +91,7 @@ public function create(array $object, bool $stickyIt = false): Entry
             $dto->title = $object['name'];
             $dto->apId = $object['id'];
 
-            if ((isset($object['attachment']) || isset($object['image'])) && $image = $this->activityPubManager->handleImages($object['attachment'])) {
+            if ((isset($object['attachment']) || isset($object['image'])) && $image = $this->activityPubManager->handleImages($object['attachment'] ?? $object['image'])) {
```
Comment (blued-gear) [inline src/Service/ActivityPub/Page.php:94]: This should also be applied to `Note`

Comment (BentiGorlich) [reply src/Service/ActivityPub/Page.php:94]: In Note we do not support the `image` property. I could add that, but I am not sure that we should...

Comment (blued-gear) [reply src/Service/ActivityPub/Page.php:94]: Ah, alright. I wasn't sure if it was forgotten to handle `image` in the Note code.

**Review by blued-gear — APPROVED** [review]
