### PR TITLE
Fix a bunch of deprecations

### LINKED ISSUE #744: revisit controllers/routes and add MapEntity where necessary
follow up of #738 

more info: https://github.com/doctrine/DoctrineBundle/pull/1762

the least that needed to be done is go over used controllers and routes, see if they used this auto mapping way to map entity into params, and add `#[MapEntity]` where necessary, so that in the end `doctrine.orm.controller_resolver.auto_mapping` could finally be disabled, by setting it to `false`

---

> Actually if I read the documentation correctly, there is a good reason why Symfony is trying to disabled automapper by default. Maybe we should set it to false (default soon) as well as use the MapEntity configuration options instead.
> 
> In the next Symfony major release this automapper option will be set to false by default for a good reason after all.
> 
> Meaning I would like to see this option to be set to false and use MapEntity

_Originally posted by @melroy89 in https://github.com/MbinOrg/mbin/issues/738#issuecomment-2084846184_

> Set to `false` and use MapEntity: https://symfony.com/doc/current/doctrine.html#mapentity-options. Which is the purpose from Symfony to deprecate this auto mapping.

_Originally posted by @melroy89 in https://github.com/MbinOrg/mbin/pull/738#discussion_r1584472650_

### PR DESCRIPTION
**Pull request by blued-gear**
@melroy89 @BentiGorlich @jwr1 please comment with log-messages about deprecations you saw in recent time. If no new deprecations are added within a week, I will mark this PR as ready.

Fixes #744

### CODE REVIEW

**Comment by melroy89** [comment]
Let me try to switch kbin.melroy.org to this branch now..

File: src/Controller/Domain/DomainBlockController.php [hunk 1]
```diff
@@ -32,7 +33,7 @@ public function block(Domain $domain, Request $request): Response
     }
 
     #[IsGranted('ROLE_USER')]
-    public function unblock(Domain $domain, Request $request): Response
+    public function unblock(#[MapEntity(mapping: ['name' => 'name'])] Domain $domain, Request $request): Response
```
Comment (BentiGorlich) [inline src/Controller/Domain/DomainBlockController.php:36]: Is it really necessary to specifcy the mapping? Wouldn't it it suffice to have a `#[MapEntity]` on there?

File: src/Controller/Entry/Comment/EntryCommentFrontController.php [hunk 2]
```diff
@@ -23,8 +23,13 @@ public function __construct(
...
 
-    public function front(?Magazine $magazine, ?string $sortBy, ?string $time, Request $request, #[MapQueryParameter] ?string $federation): Response
-    {
+    public function front(
+        ?Magazine $magazine,
+        ?string $sortBy,
+        ?string $time,
+        Request $request,
+        #[MapQueryParameter] ?string $federation,
+    ): Response {
```
Comment (BentiGorlich) [inline src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: This is not a deprecation is it? I mean style is always subjective, but I personally really don't like function declarations like this. I accept them if the definition would go beyond my screen, but this is definitely not 😅

File: src/Controller/Domain/DomainBlockController.php (hunk 1 above)
Comment (blued-gear) [reply src/Controller/Domain/DomainBlockController.php:36]: I honestly don't know. Normally `MapEntity` uses the ID, so I wanted to be on the safe side by being explicit.

Comment (BentiGorlich) [reply src/Controller/Domain/DomainBlockController.php:36]: Could you please try it?

File: src/Controller/Entry/Comment/EntryCommentFrontController.php (hunk 2 above)
Comment (blued-gear) [reply src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: I like them when there more than just a few trivial parameters (and an attribute is not trivial). In one line it goes beyond the recommended width-limit PhpStrom shows.\
But yes, style is subjective and as we have two different opinions, a third person should add judgment.

File: src/Controller/Domain/DomainBlockController.php (hunk 1 above)
Comment (blued-gear) [reply src/Controller/Domain/DomainBlockController.php:36]: I removed them and the test are still green, so it seems to be okay.

File: src/Controller/Api/Notification/NotificationPushApi.php [hunk 3]
```diff
@@ -158,6 +158,7 @@ public function deleteSubscription(
         try {
             $conn = $this->entityManager->getConnection();
             $stmt = $conn->prepare('DELETE FROM user_push_subscription WHERE user_id = :user AND api_token = :token');
+            // TODO fix deprecation
```
Comment (BentiGorlich) [inline src/Controller/Api/Notification/NotificationPushApi.php]: why a todo?

File: src/Controller/Magazine/Panel/MagazineBanController.php [hunk 4]
```diff
@@ -27,8 +28,12 @@ public function __construct(
 
     #[IsGranted('ROLE_USER')]
     #[IsGranted('moderate', subject: 'magazine')]
-    public function bans(Magazine $magazine, UserRepository $repository, Request $request): Response
-    {
+    public function bans(
+        #[MapEntity]
+        Magazine $magazine,
```
Comment (BentiGorlich) [inline src/Controller/Magazine/Panel/MagazineBanController.php]: The other style discussion aside, I do think if we're already putting each parameter on its own line, the attribute should go on the same line
```suggestion
        #[MapEntity] Magazine $magazine,
```

File: src/Controller/Entry/Comment/EntryCommentFrontController.php (hunk 2 above)
Comment (BentiGorlich) [reply src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: Maybe we should agree upon a maximum line width and configure our linter accordingly as well :thinking:

Comment (BentiGorlich) [reply src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: There is this rule in php-cs-fixer: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/multiline_promoted_properties.rst
It is not using the line width, but the parameter count.

File: src/Controller/Api/Notification/NotificationPushApi.php (hunk 3 above)
Comment (blued-gear) [reply src/Controller/Api/Notification/NotificationPushApi.php]: There I don't know how to fix it. The new way to add parameters require stating the type of the parameter (where string is the default). `$apiToken` is a class instance and the enum of available types only has NULL, INTEGER, STRING, LARGE_OBJECT, BOOLEAN, BINARY, and ASCII.

File: src/Controller/Magazine/Panel/MagazineBanController.php (hunk 4 above)
Comment (blued-gear) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: I would be okay with this. But after looking through the codebase almost all multiline parameter lists have this attribute in a separate line and I think it is not worth the effort to change all these 349 occurrences.

Comment (BentiGorlich) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: I am fine with leaving the old ones like they were, but new ones should then be in the "same line" style :thinking:

File: src/Controller/Api/Notification/NotificationPushApi.php (hunk 3 above)
Comment (BentiGorlich) [reply src/Controller/Api/Notification/NotificationPushApi.php]: I am pretty sure that you just have to call `__toString()` (or `getIdentifier`)  on it 🤔 
Or it is not working at all at the moment...

File: src/Controller/Magazine/Panel/MagazineBanController.php (hunk 4 above)
Comment (blued-gear) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: That would be inconsistent and creates an immediate itching on my brain 😅

Comment (BentiGorlich) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: I totally get that. I hate wasted space and that is why I keep arguing about the style here :sweat_smile: 
In the end these discussions only consume time, so I think it is probably not safe that time :D

File: src/Controller/Api/Notification/NotificationPushApi.php (hunk 3 above)
Comment (blued-gear) [reply src/Controller/Api/Notification/NotificationPushApi.php]: I dug into the Doctrine code and I think this snipped is relevant:

```php
foreach ($params as $param => $value) {
    if (is_int($param)) {
        $this->bindValue($param + 1, $value, ParameterType::STRING);
    } else {
        $this->bindValue($param, $value, ParameterType::STRING);
    }
}
```

So I guess the object is converted to string which means the code is broken or `AccessToken` implements its toString so that it works purely by chance.

File: src/Controller/Magazine/Panel/MagazineBanController.php (hunk 4 above)
Comment (melroy89) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: As you can see also in the official Symfony docs: https://symfony.com/doc/current/doctrine.html#mapentity-options

Attributes are often but above, to increase readability. 

In some cases the attribute can become very long, like: `#[MapEntity(expr: 'repository.findOneBy({"product": id}, {"createdAt": request.query.get("sort", "DESC")})')]`

So you definitely do **not** want to put that in front of / in-line with the parameter / argument.

File: src/Controller/Api/Notification/NotificationPushApi.php (hunk 3 above)
Comment (BentiGorlich) [reply src/Controller/Api/Notification/NotificationPushApi.php]: it implements `__toString()`

File: src/Controller/Magazine/Panel/MagazineBanController.php (hunk 4 above)
Comment (BentiGorlich) [reply src/Controller/Magazine/Panel/MagazineBanController.php]: fair

**Comment by melroy89** [comment]
New messages now in latest Symfony.

```
{"message":"User Deprecated: Since symfony/framework-bundle 7.3: Not setting the \"property_info.with_constructor_extractor\" option explicitly is deprecated because its default value will change in version 8.0.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: Not setting the \"property_info.with_constructor_extractor\" option explicitly is deprecated because its default value will change in version 8.0.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/framework-bundle/DependencyInjection/Configuration.php:1348"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:47.903629+00:00","extra":{}}
{"message":"User Deprecated: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. (DoctrineExtension.php:932 called by DoctrineExtension.php:541, https://github.com/doctrine/DoctrineBundle/pull/1804, package doctrine/doctrine-bundle)","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. (DoctrineExtension.php:932 called by DoctrineExtension.php:541, https://github.com/doctrine/DoctrineBundle/pull/1804, package doctrine/doctrine-bundle)","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/doctrine/deprecations/src/Deprecation.php:208"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:47.988578+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/dependency-injection 7.4: XML configuration format is deprecated, use YAML or PHP instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/dependency-injection 7.4: XML configuration format is deprecated, use YAML or PHP instead.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php:48"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.014911+00:00","extra":{}}


{"message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiReadLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Eav1iuP\" service.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiReadLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Eav1iuP\" service.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:68"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.721802+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $anonymousApiReadLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Eav1iuP\" service.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $anonymousApiReadLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Eav1iuP\" service.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:68"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.721839+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiDeleteLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.gNCi44s\" service.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiDeleteLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.gNCi44s\" service.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:68"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.721918+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiVoteLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.fSlmY23\" service.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiVoteLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.fSlmY23\" service.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:68"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.721990+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiReportLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Upqq_Rd\" service.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/framework-bundle 7.3: The \"Symfony\\Component\\RateLimiter\\RateLimiterFactory $apiReportLimiter\" autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead. It is being referenced by the \".service_locator.Upqq_Rd\" service.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/dependency-injection/Compiler/ResolveReferencesToAliasesPass.php:68"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:48.722049+00:00","extra":{}}
{

{"message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/validator/Constraint.php:122"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:51.447603+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/validator/Constraint.php:122"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:51.502923+00:00","extra":{}}
{"message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/validator 7.4: Support for evaluating options in the base Constraint class is deprecated. Initialize properties in the constructor of App\\Validator\\Unique instead.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/validator/Constraint.php:122"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:51.503013+00:00","extra":{}}
                   

{"message":"User Deprecated: Since symfony/var-exporter 7.3: The \"Symfony\\Component\\VarExporter\\LazyGhostTrait\" trait is deprecated, use native lazy objects instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/var-exporter 7.3: The \"Symfony\\Component\\VarExporter\\LazyGhostTrait\" trait is deprecated, use native lazy objects instead.","code":0,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/var-exporter/LazyGhostTrait.php:21"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2026-02-18T01:27:53.232301+00:00","extra":{}}
```

**Comment by BentiGorlich** [comment]
I saw another one after symfony 7.4: 

> Symfony\\Component\\RateLimiter\\RateLimiterFactory autowiring alias is deprecated and will be removed in 8.0, use \"RateLimiterFactoryInterface\" instead.

**Comment by blued-gear** [comment]
> Not setting the "property_info.with_constructor_extractor" option explicitly is deprecated

The default until version 8 is `false` but I set it to `true` now, as I think it might be useful. If someone knows something about this causing issues, we can revert it.

File: src/Controller/Entry/Comment/EntryCommentFrontController.php (hunk 2 above)
Comment (blued-gear) [reply src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: The rules only applies to constructor property-declarations. There is [a rule](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/method_argument_space.rst) for functions, but it can only be configured to always or never expand the param list onto newlines.

Comment (BentiGorlich) [reply src/Controller/Entry/Comment/EntryCommentFrontController.php:32]: meh ok...

**Review by melroy89 — APPROVED** [review]
If we need a follow-up work, we can always create an additional PR.

Also some deprecation fixes are part of another PR already: https://github.com/MbinOrg/mbin/pull/2026/

And some remaining deprecation are not part of our project, but due to vendor packages. So updating our composer packages would also help to resolve those remaining deprecations.
