### PR TITLE
Url Ids should not be extracted as a hashtag

### LINKED ISSUE #1548: Undesired tagging of a post when a link has the # character
**Describe the bug**
Undesired tagging of a post when a link in the post body includes the # character.

**On which Mbin instance did you find the bug?**
kbin.melroy.org

**Which Mbin version was running on the instance?**
1.8.1

**To Reproduce**
1. Create a new thread.
2. Put a link in the body that includes the `#` character. For example, put in `https://test.notrealwebsite284/#hello`.
3. Click the top left hamburger menu icon and scroll to the Thread section, and see that you now have a tag that matches whatever followed the `#` character in the link. If you followed my example, your post is now tagged #hello.
4. Edit the post, clicking the X next to the tag to attempt to remove the tag. Notice that it stays anyways, because of the content in the link following the `#` character.

**Expected behavior**
I expect the `#` character to be ignored for tagging purposes when it is in a link. It can cause trouble otherwise. Imagine linking https://news.site375/the-summer-blockbuster-movie-broke-sales-records/#heading. The way things are now, you will end up forced to have the tag #heading on your post. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 17.1.2
 - Browser: Safari
 - Browser Version: 17.1

### PR DESCRIPTION
**Pull request by BentiGorlich**
- our `TagExtractor` extracted url ids as hashtags before. Add a testcase for it and fix that

Closes #1548

### CODE REVIEW

File: src/Utils/UrlUtils.php [hunk 1]
```diff
@@ -39,4 +39,17 @@ public static function getCacheKeyForMarkdownMagazineMention(string $url): strin
 
         return "markdown_magazine_mention_$key";
     }
+
+    public static function extractUrlsFromString(string $text): array
+    {
+        $words = preg_split('/[ \n\[\]()]/', $text);
```
Comment (melroy89) [inline src/Utils/UrlUtils.php:45]: Would you mind to move the regex to our RegPatterns Utils file? https://github.com/MbinOrg/mbin/blob/main/src/Utils/RegPatterns.php

Comment (melroy89) [reply src/Utils/UrlUtils.php:45]: Nevermind.. I do not think this is really a regex. right?

Comment (BentiGorlich) [reply src/Utils/UrlUtils.php:45]: will di

**Review by melroy89 — APPROVED** [review]
